package com.z2daddy.uip.pojo;
// Generated 2017-3-6 16:40:52 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TSceIntrointfbuffsetId generated by hbm2java
 */
@Embeddable
public class TSceIntrointfbuffsetId implements java.io.Serializable {

	private String tasktag;
	private String touchid;

	public TSceIntrointfbuffsetId() {
	}

	public TSceIntrointfbuffsetId(String tasktag, String touchid) {
		this.tasktag = tasktag;
		this.touchid = touchid;
	}

	@Column(name = "TASKTAG", nullable = false, length = 3)
	public String getTasktag() {
		return this.tasktag;
	}

	public void setTasktag(String tasktag) {
		this.tasktag = tasktag;
	}

	@Column(name = "TOUCHID", nullable = false, length = 30)
	public String getTouchid() {
		return this.touchid;
	}

	public void setTouchid(String touchid) {
		this.touchid = touchid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TSceIntrointfbuffsetId))
			return false;
		TSceIntrointfbuffsetId castOther = (TSceIntrointfbuffsetId) other;

		return ((this.getTasktag() == castOther.getTasktag()) || (this.getTasktag() != null
				&& castOther.getTasktag() != null && this.getTasktag().equals(castOther.getTasktag())))
				&& ((this.getTouchid() == castOther.getTouchid()) || (this.getTouchid() != null
						&& castOther.getTouchid() != null && this.getTouchid().equals(castOther.getTouchid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTasktag() == null ? 0 : this.getTasktag().hashCode());
		result = 37 * result + (getTouchid() == null ? 0 : this.getTouchid().hashCode());
		return result;
	}

}
