package com.z2daddy.uip.pojo;
// Generated 2017-3-6 16:40:52 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TSceIntrointfbuffgetId generated by hbm2java
 */
@Embeddable
public class TSceIntrointfbuffgetId implements java.io.Serializable {

	private String touchid;
	private String seqtag;

	public TSceIntrointfbuffgetId() {
	}

	public TSceIntrointfbuffgetId(String touchid, String seqtag) {
		this.touchid = touchid;
		this.seqtag = seqtag;
	}

	@Column(name = "TOUCHID", nullable = false, length = 30)
	public String getTouchid() {
		return this.touchid;
	}

	public void setTouchid(String touchid) {
		this.touchid = touchid;
	}

	@Column(name = "SEQTAG", nullable = false, length = 3)
	public String getSeqtag() {
		return this.seqtag;
	}

	public void setSeqtag(String seqtag) {
		this.seqtag = seqtag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TSceIntrointfbuffgetId))
			return false;
		TSceIntrointfbuffgetId castOther = (TSceIntrointfbuffgetId) other;

		return ((this.getTouchid() == castOther.getTouchid()) || (this.getTouchid() != null
				&& castOther.getTouchid() != null && this.getTouchid().equals(castOther.getTouchid())))
				&& ((this.getSeqtag() == castOther.getSeqtag()) || (this.getSeqtag() != null
						&& castOther.getSeqtag() != null && this.getSeqtag().equals(castOther.getSeqtag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTouchid() == null ? 0 : this.getTouchid().hashCode());
		result = 37 * result + (getSeqtag() == null ? 0 : this.getSeqtag().hashCode());
		return result;
	}

}
